apiVersion: apps/v1
kind: Deployment
metadata:
  name: xchemspa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xchemspa
  template:
    metadata:
      labels:
        app: xchemspa
    spec:
      securityContext:
        runAsUser: 1217611
        runAsGroup: 1217611
      volumes:
      - name: dls
        hostPath:
          path: /dls
          type: Directory
      containers:
      - name: xchemspa
        securityContext:
            privileged: false
        image: gcr.io/diamond-privreg/soakdb:1.0
        ports:
      - name: http
          containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: xchemspa
spec:
  ports:
  - name: http
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: xchemspa
