# Generated by Django 3.1.6 on 2021-02-03 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('title', models.CharField(blank=True, max_length=10, null=True)),
                ('fedids', models.TextField(blank=True, null=True)),
                ('industry_user', models.BooleanField(default=True)),
                ('libraries', models.ManyToManyField(blank=True, to='API.Library')),
                ('protein', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='API.protein')),
                ('subsets', models.ManyToManyField(blank=True, to='API.LibrarySubset')),
            ],
        ),
        migrations.AddField(
            model_name='soakdbcompound',
            name='proposal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exp_compounds', to='API.proposals'),
        ),
    ]
