export const display_options = [
			["show_well", "Well"],
			["show_structure", "2D Structure"],
			["show_code", "Compound Code"],
			["show_smiles", "SMILES"],
			["show_concentration", "Concentration"],
			["show_mol_wt", "Molecular Weight"],
			["show_tpsa", "TPSA"],
			["show_logp", "LogP"],
			["show_heavy_atom_count", "Heavy Atom Count"],
			["show_heavy_atom_mol_wt", "Avg. Heavy Atom Mol. Weight"], 
			["show_nhoh_count", "No. of NHs or OHs"], 
			["show_no_count", "No. of Nitrogens and Oxygens"], 
			["show_num_h_acceptors", "No. of Hydrogen Bond Acceptors"], 
			["show_num_h_donors", "No. of Hydrogen Bond Donors"], 
			["show_num_het_atoms", "No. of Heteroatoms"], 
			["show_num_rot_bonds", "No. of Rotatable Bonds"], 
			["show_num_val_electrons", "No. of Valence Electrons"], 
			["show_ring_count", "No. of Rings"], 
		];

export const descriptor_names = [
	"mol_wt", 
	"tpsa", 
	"log_p", 
	"heavy_atom_count",
	"heavy_atom_mol_wt", 
	"nhoh_count" , 
	"no_count", 
	"num_h_acceptors", 
	"num_h_donors", 
	"num_het_atoms", 
	"num_rot_bonds", 
	"num_val_electrons", 
	"ring_count"]
