# Generated by Django 3.1.5 on 2021-07-26 21:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ispybauthorization',
            name='project',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='ispybauthorization',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ispybauthorization',
            name='proposal_visit',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='ispybauthorization',
            unique_together={('project', 'proposal_visit')},
        ),
    ]
