# Generated by Django 3.1.5 on 2021-08-20 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_auth', '0001_initial'),
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='auth',
        ),
        migrations.AddField(
            model_name='project',
            name='auth',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_obj', to='django_auth.ispybauthorization'),
        ),
    ]
