# Generated by Django 3.1.5 on 2021-08-24 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_auth', '0001_initial'),
        ('API', '0002_auto_20210820_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='auth',
        ),
        migrations.AddField(
            model_name='project',
            name='auth',
            field=models.ManyToManyField(blank=True, related_name='project_obj', to='django_auth.IspybAuthorization'),
        ),
    ]
