# Generated by Django 3.1.6 on 2021-02-03 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_auto_20210203_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crystal',
            name='crystal_name',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='crystal',
            name='target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='API.target'),
        ),
        migrations.AlterField(
            model_name='crystal',
            name='visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='API.soakdbfiles'),
        ),
    ]
