# Generated by Django 3.1.5 on 2021-07-30 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_auto_20210726_2110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='fedids',
        ),
        migrations.RemoveField(
            model_name='project',
            name='proposal',
        ),
        migrations.RemoveField(
            model_name='project',
            name='title',
        ),
    ]
