# Generated by Django 3.1.5 on 2021-03-03 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_auto_20210216_1854'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='crystal',
            unique_together={('crystal_name', 'visit', 'product')},
        ),
        migrations.RemoveField(
            model_name='crystal',
            name='compound',
        ),
    ]
