# Generated by Django 3.1.5 on 2021-04-12 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_auto_20210324_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='compounds',
            name='heavy_atom_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compounds',
            name='heavy_atom_mol_wt',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compounds',
            name='log_p',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compounds',
            name='mol_wt',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compounds',
            name='nhoh_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compounds',
            name='no_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compounds',
            name='num_h_acceptors',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compounds',
            name='num_h_donors',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compounds',
            name='num_het_atoms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compounds',
            name='num_rot_bonds',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compounds',
            name='num_val_electrons',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compounds',
            name='ring_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compounds',
            name='tpsa',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
