# Generated by Django 3.1.5 on 2021-04-12 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0009_auto_20210412_1703'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libraryplate',
            old_name='name',
            new_name='barcode',
        ),
    ]
