# Generated by Django 3.1.5 on 2021-04-12 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0010_auto_20210412_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libraryplate',
            name='barcode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
