# Generated by Django 3.1.5 on 2021-04-12 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0011_auto_20210412_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcewell',
            name='compound',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='API.compounds'),
        ),
        migrations.AlterField(
            model_name='sourcewell',
            name='library_plate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compounds', to='API.libraryplate'),
        ),
        migrations.AlterField(
            model_name='sourcewell',
            name='well',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
