# Generated by Django 3.1.5 on 2021-04-12 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0012_auto_20210412_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librarysubset',
            name='compounds',
            field=models.ManyToManyField(blank=True, to='API.Compounds'),
        ),
        migrations.AlterField(
            model_name='librarysubset',
            name='library',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='API.library'),
        ),
        migrations.AlterField(
            model_name='librarysubset',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='librarysubset',
            name='origin',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
