# Generated by Django 3.1.5 on 2021-04-12 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0013_auto_20210412_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preset',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='preset',
            name='subsets',
            field=models.ManyToManyField(blank=True, to='API.LibrarySubset'),
        ),
    ]
