# Generated by Django 3.1.5 on 2021-04-12 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0014_auto_20210412_1710'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='reference',
            table=None,
        ),
        migrations.AlterModelTable(
            name='tasks',
            table=None,
        ),
    ]
