# Generated by Django 3.1.5 on 2021-04-12 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0015_auto_20210412_1711'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proposals',
            old_name='name',
            new_name='proposal',
        ),
    ]
