# Generated by Django 3.1.5 on 2021-04-12 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0017_visit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crystalplate',
            name='drop_volume',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='crystalplate',
            name='name',
            field=models.CharField(default='new_plate', max_length=100),
        ),
        migrations.AlterField(
            model_name='crystalplate',
            name='plate_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
