# Generated by Django 3.1.5 on 2021-04-12 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0018_auto_20210412_1722'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpaCompound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('library_name', models.CharField(max_length=100)),
                ('library_plate', models.CharField(max_length=100)),
                ('well', models.CharField(max_length=4)),
                ('code', models.CharField(max_length=100)),
                ('smiles', models.CharField(max_length=256)),
                ('visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='API.visit')),
            ],
        ),
    ]
