# Generated by Django 3.1.5 on 2021-04-12 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0019_spacompound'),
    ]

    operations = [
        migrations.AddField(
            model_name='crystal',
            name='soakdb_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='API.soakdbfiles'),
        ),
        migrations.AlterField(
            model_name='crystal',
            name='visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='API.visit'),
        ),
        migrations.AlterModelTable(
            name='crystal',
            table=None,
        ),
    ]
