# Generated by Django 3.1.5 on 2021-04-12 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0020_auto_20210412_1727'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompoundCombination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(blank=True, null=True)),
                ('related_crystals', models.CharField(blank=True, max_length=64, null=True)),
                ('compounds', models.ManyToManyField(to='API.SpaCompound')),
                ('visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='API.visit')),
            ],
        ),
    ]
