# Generated by Django 3.1.5 on 2021-04-12 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0021_compoundcombination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solventnotes',
            name='cryo',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='solventnotes',
            name='cryo_concentration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='solventnotes',
            name='solvent',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
