# Generated by Django 3.1.5 on 2021-04-12 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0022_auto_20210412_1728'),
    ]

#    operations = [
#        migrations.AlterField(
#            model_name='lab',
#            name='compound',
#            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='API.spacompound'),
#        ),
#   ]
