# Generated by Django 3.1.5 on 2021-04-12 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0023_auto_20210412_1730'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SoakDBCompound',
        ),
    ]
