# Generated by Django 3.1.5 on 2021-04-12 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0026_auto_20210412_2010'),
    ]

    operations = [
        
    ]
