# Generated by Django 3.1.5 on 2021-04-12 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0028_solventtestingdata'),
    ]

#    operations = [
#        migrations.AlterModelTable(
#            name='dimple',
#            table=None,
#        ),
#    ]
