# Generated by Django 3.1.5 on 2021-04-12 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0029_auto_20210412_2033'),
    ]

    operations = [
#        migrations.AlterModelTable(
#            name='dimple',
#            table=None,
#        ),
         migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_collection_visit', models.CharField(blank=True, max_length=64, null=True)),
                ('harvest_status', models.CharField(blank=True, max_length=64, null=True)),
                ('mounting_result', models.CharField(blank=True, max_length=64, null=True)),
                ('mounting_time', models.CharField(blank=True, max_length=64, null=True)),
                ('visit', models.CharField(blank=True, max_length=64, null=True)),
                ('puck', models.CharField(blank=True, max_length=100, null=True)),
                ('position', models.CharField(blank=True, max_length=100, null=True)),
                ('pin_barcode', models.CharField(blank=True, max_length=100, null=True)),
                ('arrival_time', models.DateTimeField(blank=True, null=True)),
                ('mounted_timestamp', models.DateTimeField(blank=True, null=True)),
                ('ispyb_status', models.CharField(blank=True, max_length=100, null=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='API.batch')),
                ('compound_combination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='API.compoundcombination')),
                ('crystal_name', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='API.crystal')),
                ('single_compound', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='API.spacompound')),
                ('solvent_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='API.solventtestingdata')),
            ],
        ),
    ]
