# Generated by Django 3.1.5 on 2021-04-12 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0030_auto_20210412_2050'),
    ]

#    operations = [
#        migrations.DeleteModel(
#            name='Dimple',
#        ),
#    ]
