# Generated by Django 3.1.5 on 2021-04-12 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0031_delete_dimple'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dimple',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mtz_path', models.CharField(blank=True, max_length=255, null=True)),
                ('pdb_path', models.CharField(blank=True, max_length=255, null=True)),
                ('r_free', models.FloatField(blank=True, null=True)),
                ('res_high', models.FloatField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('crystal_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='API.crystal')),
                ('reference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='API.reference')),
            ],
            options={
                'unique_together': {('pdb_path', 'mtz_path')},
            },
        ),
    ]
