# Generated by Django 3.1.5 on 2021-04-13 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0032_dimple'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='refinement',
            table=None,
        ),
    ]
