# Generated by Django 3.1.5 on 2021-04-13 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0033_auto_20210413_0323'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='metadata',
            table=None,
        ),
    ]
