# Generated by Django 3.1.5 on 2021-04-13 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0034_auto_20210413_0326'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ligand',
            table=None,
        ),
    ]
