# Generated by Django 3.1.5 on 2021-05-04 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0035_auto_20210413_0330'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlateOpening',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('reason', models.TextField(blank=True, null=True)),
                ('plate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opened', to='API.libraryplate')),
            ],
        ),
    ]
