# Generated by Django 3.1.5 on 2021-05-04 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0037_compounds_mol_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='heavy_atom_count_graph',
            field=models.ImageField(blank=True, null=True, upload_to='images/graphs/heavy_atom_count/'),
        ),
        migrations.AddField(
            model_name='library',
            name='heavy_atom_mol_wt_graph',
            field=models.ImageField(blank=True, null=True, upload_to='images/graphs/heavy_atom_mol_wt/'),
        ),
        migrations.AddField(
            model_name='library',
            name='log_p_graph',
            field=models.ImageField(blank=True, null=True, upload_to='images/graphs/log_p/'),
        ),
        migrations.AddField(
            model_name='library',
            name='mol_wt_graph',
            field=models.ImageField(blank=True, null=True, upload_to='images/graphs/mol_wt/'),
        ),
        migrations.AddField(
            model_name='library',
            name='nhoh_count_graph',
            field=models.ImageField(blank=True, null=True, upload_to='images/graphs/nhoh_count/'),
        ),
        migrations.AddField(
            model_name='library',
            name='no_count_graph',
            field=models.ImageField(blank=True, null=True, upload_to='images/graphs/no_count/'),
        ),
        migrations.AddField(
            model_name='library',
            name='num_h_acceptors_graph',
            field=models.ImageField(blank=True, null=True, upload_to='images/graphs/num_h_acceptors/'),
        ),
        migrations.AddField(
            model_name='library',
            name='num_h_donors_graph',
            field=models.ImageField(blank=True, null=True, upload_to='images/graphs/num_h_donors/'),
        ),
        migrations.AddField(
            model_name='library',
            name='num_het_atoms_graph',
            field=models.ImageField(blank=True, null=True, upload_to='images/graphs/num_het_atoms/'),
        ),
        migrations.AddField(
            model_name='library',
            name='num_rot_bonds_graph',
            field=models.ImageField(blank=True, null=True, upload_to='images/graphs/num_rot_bonds/'),
        ),
        migrations.AddField(
            model_name='library',
            name='num_val_electrons_graph',
            field=models.ImageField(blank=True, null=True, upload_to='images/graphs/num_val_electrons/'),
        ),
        migrations.AddField(
            model_name='library',
            name='ring_count_graph',
            field=models.ImageField(blank=True, null=True, upload_to='images/graphs/ring_count/'),
        ),
        migrations.AddField(
            model_name='library',
            name='tpsa_graph',
            field=models.ImageField(blank=True, null=True, upload_to='images/graphs/tpsa/'),
        ),
    ]
