# Generated by Django 3.1.5 on 2021-05-05 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0038_auto_20210504_1513'),
    ]

    operations = [
        migrations.CreateModel(
            name='SWStatuschange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('activation', models.BooleanField(default=False)),
                ('source_well', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_changes', to='API.sourcewell')),
            ],
        ),
    ]
